version: '3.2'

services:
  iris:
    build: .
    restart: always
    container_name: iris-community-2019.3
    ports:
    - "51773:1972"
    - "52773:52773"
    volumes:
    - ./datatransform-test:/app/datatransform-test
    - ./src:/app/src
